GET https://localhost:7277/catalog


POST https://localhost:7277/catalog
Content-Type: application/json

{
    "name":"Shoes",
    "description": "Ohio State shoes",
    "brand": "Nike",
    "price": 129.99
}